# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import resource

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        Dialog.setFont(font)
        Dialog.setStyleSheet("")
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(-2, -2, 411, 311))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setAutoFillBackground(False)
        self.page.setStyleSheet("background-image: url(:/newPrefix/mountain.jpg);\n"
"")
        self.page.setObjectName("page")
        self.OkayButton = QtWidgets.QPushButton(self.page)
        self.OkayButton.setGeometry(QtCore.QRect(200, 260, 93, 28))
        self.OkayButton.setObjectName("OkayButton")
        self.CancelButton = QtWidgets.QPushButton(self.page)
        self.CancelButton.setGeometry(QtCore.QRect(300, 260, 93, 28))
        self.CancelButton.setObjectName("CancelButton")
        self.ParkNameWidget = QtWidgets.QListWidget(self.page)
        self.ParkNameWidget.setGeometry(QtCore.QRect(10, 70, 381, 171))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ParkNameWidget.setFont(font)
        self.ParkNameWidget.setAutoFillBackground(False)
        self.ParkNameWidget.setStyleSheet("color: rgb(255, 255, 255);")
        self.ParkNameWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.ParkNameWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.ParkNameWidget.setUniformItemSizes(False)
        self.ParkNameWidget.setWordWrap(False)
        self.ParkNameWidget.setSelectionRectVisible(False)
        self.ParkNameWidget.setObjectName("ParkNameWidget")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.ParkNameWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.ParkNameWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.ParkNameWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ParkNameWidget.addItem(item)
        self.RouteLabel = QtWidgets.QLabel(self.page)
        self.RouteLabel.setGeometry(QtCore.QRect(100, 20, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.RouteLabel.setFont(font)
        self.RouteLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.RouteLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.RouteLabel.setObjectName("RouteLabel")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(154, 154, 154);")
        self.label.setObjectName("label")
        self.graphicsView = QtWidgets.QGraphicsView(self.page_2)
        self.graphicsView.setGeometry(QtCore.QRect(10, 40, 371, 111))
        self.graphicsView.setObjectName("graphicsView")
        self.listWidget = QtWidgets.QListWidget(self.page_2)
        self.listWidget.setGeometry(QtCore.QRect(10, 200, 241, 81))
        self.listWidget.setObjectName("listWidget")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(20, 170, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(171, 171, 171);")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.page_2)
        self.pushButton.setGeometry(QtCore.QRect(280, 220, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        self.OkayButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))
        self.pushButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2))
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.OkayButton.setText(_translate("Dialog", "OK"))
        self.CancelButton.setText(_translate("Dialog", "Cancel"))
        self.ParkNameWidget.setSortingEnabled(False)
        __sortingEnabled = self.ParkNameWidget.isSortingEnabled()
        self.ParkNameWidget.setSortingEnabled(False)
        item = self.ParkNameWidget.item(0)
        item.setText(_translate("Dialog", "Yosemite National Park"))
        item = self.ParkNameWidget.item(1)
        item.setText(_translate("Dialog", "Big Bend State Park"))
        item = self.ParkNameWidget.item(2)
        item.setText(_translate("Dialog", "Yellow Stone National Park"))
        self.ParkNameWidget.setSortingEnabled(__sortingEnabled)
        self.RouteLabel.setText(_translate("Dialog", "Choose Your Route"))
        self.label.setText(_translate("Dialog", "Weather"))
        self.label_2.setText(_translate("Dialog", "Choose Your Route"))
        self.pushButton.setText(_translate("Dialog", "Continue"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())